### ISSUE TITLE
computer crash when running the code

### ISSUE THREAD

**Issue by HeyLinyuhao** [ZihanWangKi/XClass#1]
Hi @ZihanWangKi 

It is remarkable work!

I followed your work those couple days on my own pc (ubuntu 18.04 with 1080ti). When I tried to run your code (in static_representation.py line 128 : for text in tqdm(data): xxx), the computer dead for some unknown reasons. No error or warnings,  just stuck there. I also tried other datasets, they all died when the progress bar reached about 80%. Is there any way to solve it?

Cheers,
Yuhao

**Comment by ZihanWangKi** [comment]
Hi Yuhao,

I'm not sure what exactly could have happened as I am able to run the code. My guess is that It is possible that your pc's memory is not sufficient. The smallest among the seven is NYT-Small and you can try that first. You may even create a smaller copy by selecting a few documents from it.  If this is the case, I would strongly suggest running it on somewhere that has enough memory.
Let me know if this is the case :)

Best,
Zihan

**Comment by lakshaymehra** [comment]
Hi @ZihanWangKi,

Thank you for this really cool paper and repository! I have used XClass on my own datasets and the results are pretty impressive!

As mentioned by @HeyLinyuhao , the static_representations.py updates the word_vocab dictionary in a for loop which takes up a lot of RAM for large datasets. 

I have been trying to think of a replacement for this but have not found a solution so far. 

1. Is there any way to possibly reduce the memory consumption by avoiding the word_vocab dictionary update inside the loop? 

2. Can you please specify the hardware specifications like RAM, Number of GPUs, Disk Space, etc. which you must have used for large datasets that have (say) over a million examples?

Looking forward to your response,

Thanks and Regards,

Lakshay.

**Comment by ZihanWangKi** [comment]
Hi @lakshaymehra ,

Thanks for your interest! 
The concern about the memory requirement is indeed valid and important. Let me first define a few notations for a clearer explanation. Let me denote `V` as the vocabulary size, `d = 768` as the BERT repr dimension, and `C` as the corpus size. The current implementation requires a memory of `C * d` as it is saving everything. The best we can hope for is `V * d` as this part is pretty much unavoidable during computing the class representations. And there is a way to do this:
1. Pre-compute all the vocabulary. This means finding all words that occur at least min_occurrence times. 
2. For each vocabulary word, we need to maintain two values, the sum of all representations of its occurrences, and the number of occurrences we see. Then, for each document, we pass it to BERT, obtain the presentations, and update the words respectively. For example, DOC = "I eat salmon" is the document, what we do is: vocab_representaition_sum['I'] += repr['DOC'][0], vocab_representaition_cnt['I'] += 1. And similarly for 'eat' and 'salmon'. 
3. To get the average in the end, we divide the sum representations by the count.

For hardware specifications:
The largest dataset we used is DBpedia with around half a million of examples. I did not pay attention to how much RAM it took, but with the previous method, it could be significantly reduced. We used a single GPU with 48G memory (the actual consumption is ~28G, this does not grow with # of examples), and the disk space took is < 10 G.

**Comment by lakshaymehra** [comment]
Hi @ZihanWangKi,

Thank you for your detailed response!

I implemented the 3 steps which you mentioned by updating the static_representations.py file with the following code:   
```   
tokenization_info = []
import re
from collections import Counter
counts = Counter()
import string

for text in tqdm(data):
  tokenized_text, tokenized_to_id_indicies, tokenids_chunks = prepare_sentence(tokenizer, text)
  counts.update(word.translate(str.maketrans('','',string.punctuation)) for word in tokenized_text)
  
del counts['']
updated_counts = {k: c for k, c in counts.items() if c >= args.vocab_min_occurrence}
word_rep = {}
word_count = {}

for text in tqdm(data):
  tokenized_text, tokenized_to_id_indicies, tokenids_chunks = prepare_sentence(tokenizer, text)
  tokenization_info.append((tokenized_text, tokenized_to_id_indicies, tokenids_chunks))
  contextualized_word_representations = handle_sentence(model, args.layer, tokenized_text,
                                   tokenized_to_id_indicies, tokenids_chunks)
  for i in range(len(tokenized_text)):
    word = tokenized_text[i]
    if word in updated_counts.keys():
      if word not in word_rep:
        word_rep[word] = 0
        word_count[word] = 0
      word_rep[word] += contextualized_word_representations[i]
      word_count[word] += 1
  
word_avg = {}
for k,v in word_rep.items():
  word_avg[k] = word_rep[k]/word_count[k]

vocab_words = list(word_avg.keys())
static_word_representations = list(word_avg.values())
vocab_occurrence = list(word_count.values()) 

with open(os.path.join(data_folder, f"tokenization_lm-{args.lm_type}-{args.layer}.pk"), "wb") as f:
  pk.dump({
      "tokenization_info": tokenization_info,
  }, f, protocol=4)

with open(os.path.join(data_folder, f"static_repr_lm-{args.lm_type}-{args.layer}.pk"), "wb") as f:
  pk.dump({
      "static_word_representations": static_word_representations,
      "vocab_words": vocab_words,
      "word_to_index": {v: k for k, v in enumerate(vocab_words)},
      "vocab_occurrence": vocab_occurrence,
  }, f, protocol=4)
```

The RAM consumption was very very low compared to the original implementation and the time taken was almost the same. Is this the exact implementation that you suggested or do you think this can be further optimized?


Thanks and Regards,

Lakshay.

**Comment by ZihanWangKi** [comment]
Hi @lakshaymehra ,

This is some great work and is exactly what I meant for. A minor concern is that it may be better to specify the order when converting word_avg and word_count to lists, since different python versions may behave differently on ordering. Other than that this looks great. I do plan to revise the code a bit in the following two weeks, so it would be extremely helpful if you can push a PR (after maybe a successful experiment on NYT-Small. You can run it till the clustering stage and check the performance). 

Thanks,
Zihan

**Comment by lakshaymehra** [comment]
Hi @ZihanWangKi ,

Thank you for the appreciation!

You are right about preserving the insertion ordering of the dictionaries and an alternative would be to use OrderedDict for initializing word_avg and word_count. However, I think OrderedDict consumes a bit more memory and is a bit slower as well. Also, from Python 3.7+ I guess all dictionaries will preserve the insertion order too. So, I guess for users of older Python versions, OrderedDict might be a good option. 

I conducted experiments on NYT-Small to verify the modified code's results and the F1 scores are identical to those mentioned in the original paper. So, I will push a PR today.

Thanks and Regards,

Lakshay.

**Comment by ZihanWangKi** [comment]
@lakshaymehra Thanks so much for this!
Also, @HeyLinyuhao I am closing this issue as this new pr should resolve your problem. But if it does not, feel free to reopen it.
