### ISSUE TITLE
XClass Assumptions :

### ISSUE THREAD

**Issue by lakshaymehra** [ZihanWangKi/XClass#2]
Hi @ZihanWangKi ,

Thank you this amazing repository!

I wanted to ask you about the following assumptions of the XClass paper:

1. "The class name should be present in the input corpus because we average the contextualized representations of all its occurrences in the input corpus". 

2. "Each word in a sentence (document) is similar to its desired class’s representation or unrelated to all classes." 

My observations after conducting various experiments with XClass is that it works really nicely if both these assumptions hold true in the dataset.

However, for tasks like Fine-grained sentiment analysis, and for datasets with closely related classes, XClass tends to give lower accuracies. 

For such datasets, what would be your recommendations for achieving better results? Is there any recommended way of choosing the 'class names' in the classes.txt for datasets where either of these assumptions might get violated?

Looking forward to your response,

Thanks and Regards,

Lakshay.

**Comment by ZihanWangKi** [comment]
Hi @lakshaymehra,

Thanks for your interest! 
1. In the case of non-existent class names, we usually choose the word that is the most similar and exists in the corpus. You can take https://github.com/ZihanWangKi/XClass/tree/main/data/datasets/20News as an example. We did not try different class names for the datasets, but a guess is that you can check a few occurrences of your choice, and see if it is really talking about that topic.
2. For fine-grained experiments, we do not expect the model to work well in an end-to-end fashion, as shown in Table 4 in our [arxiv version](https://arxiv.org/pdf/2010.12794.pdf). If you are given a hierarchy of the classes, it is preferred to perform the experiment on the hierarchy --- for each set of children classes in the hierarchy, split the documents on that set, and propagate the documents to the corresponding child. 
3. I have not conducted experiments on fine-grained sentiment datasets. My suggestion is to probably take a look at the class words found first, and see if they separate the fine-grained sentiment clearly.

Hope this helps,
Zihan

**Comment by lakshaymehra** [comment]
Hi @ZihanWangKi ,

Thank you for the clarifications!

Best Regards,

Lakshay.
