### ISSUE TITLE
Error with new dataset

### ISSUE THREAD

**Issue by hoodashailok** [ZihanWangKi/XClass#6]
Hi, I am using a new dataset with 4 classes. I saved the raw newline separated sentences (4000) in dataset.txt file and 4 class name in classes.txt file, one class name each line. When I run ./run.sh 1 path-to-data-folder then it does the following
Finish reading data                                                                                                                                                                                        
  0%|                                                                                                                                                                             | 0/4000 [00:00<?, ?it/s]
101 102                                                                                                                                                                                                    
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:00<00:00, 5931.04it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:36<00:00, 110.42it/s]         
Finish reading data
Empty Sentence (or sentence with no words that have enough frequency)                                                                                                                                      
  1%|██▏                                                                                                                                                                 | 52/4000 [00:00<00:46, 84.34it/s]
Empty Sentence (or sentence with no words that have enough frequency)                                                                                                                                      
  2%|███▋                                                                                                                                                                | 90/4000 [00:01<00:46, 84.18it/s]
......
Empty Sentence (or sentence with no words that have enough frequency)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4000/4000 [00:35<00:00, 111.48it/s]
class_oriented_document_representations.py:214: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths
 or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  document_representations = np.array(document_representations)
Finish getting document representations
pca64.clusgmm.bbu-12.mixture-100.42

Then the following error
Traceback (most recent call last):
  File "document_class_alignment.py", line 122, in <module>
    main(args.dataset_name, args.pca, args.cluster_method, args.lm_type, args.document_repr_type, args.random_state)
  File "document_class_alignment.py", line 58, in main
    repr_prediction = np.argmax(cosine_similarity_embeddings(document_representations, class_representations),
  File "/home/skamila/Sabyasachi/Huawei/Baselines/XClass/scripts/utils.py", line 34, in cosine_similarity_embeddings
    return np.dot(emb_a, np.transpose(emb_b)) / np.outer(np.linalg.norm(emb_a, axis=1), np.linalg.norm(emb_b, axis=1))
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (4000,) and (768,2) not aligned: 4000 (dim 0) != 768 (dim 0)

Can anyone help? Thank you (Btw it works well using AGnews data)

**Comment by ZihanWangKi** [comment]
Hi, 

I don't recognize what could have happened looking at this error log. I was able to run the scripts. Can you help me do the following so that we can debug it?
1. Can you first try running with our data included in the google drive link under data/? That will help verify whether it is a data problem or a scripting problem.
2. It would be also helpful to include a diff of scripts you have changed (if that is not a lot), check if the repo is up-to-data, and maybe a few lines of how your data looks like. Then I might be able to tell what happened.
3. The message "Empty Sentence (or sentence with no words that have enough frequency)" is not critical, it simply means that the sentence does not contain words with enough frequency in the corpus. If the message does not appear too frequently, then it's fine.

**Comment by hoodashailok** [comment]
Hi, Thanks for your reply.
1. I have tried with AGNews data and it works absolutely fine.
2. I have not done any changes to the scripts or any .py files. I just put a new dataset inside data/datasets folder with datasets.txt and classess.txt.
Few lines from the data:
_cast is not available in this app unable to play download movie direct on tv
if i could give it 0 stars i would. i got 42 new songs and after i refreshed, you deleted them all
limits freedom of speech selectively; double standards for allowing content
music won't play. i think this worked once in the 2 months i had it. htc inspire
i paid 149 via globe tel. and using my fb account, but still i receive ads, 6 skips per hour and unable to download music.... such a waste of money.
do not update dont work what so ever_

3. I am getting the message for 245 times on a 4000 lines of sentences

**Comment by ZihanWangKi** [comment]
My hypothesis is that there is a sentence that got tokenized into an empty list. You may add an assert 
`assert len(contextualized_word_representations) != 0`
after this [line](https://github.com/ZihanWangKi/XClass/blob/355b7a06fb193d329ae647ea79761b92ed2e6cc5/scripts/class_oriented_document_representations.py#L84) to see if that is the case. If there is indeed such a sentence, I suggest looking into the dataset and remove it.

**Comment by hoodashailok** [comment]
Hi, Thanks a lot. There were indeed some words in the sentence which were getting cleaned by the preprocessing_utils.py. Specially any emojis are being cleaned. So, Each line should contain atleast a single clean word. Now, it's working fine.
