### ISSUE TITLE
multiple word classes, multi-label, and confidence scores

### ISSUE THREAD

**Issue by bruffridge** [ZihanWangKi/XClass#7]
Hi,

I enjoyed reading your paper, and I'm considering applying it to a research project I'm working on. I have a few questions:

1. Do class names need to be a single word?
2. Can X-Class perform multi-label text classification?
3. Can X-Class output confidence scores for each class predicted for a document for result ranking purposes?. IE. D1 has two predicted classes and confidence scores (sports=.9, business=.6), D2 has the same two predicted classes (sports=.8, business=.7). The ranking for the sports topic would be D1,D2; the ranking for the business topic would be D2,D1.

Thanks

**Comment by ZihanWangKi** [comment]
Hi,

Extremely sorry for the late response.
1. Currently we assumed the class name to be a single word, as we need to extract a representation from it. If it is a multi-word, I guess the first representation or the average representation would also work.
2. It can not do so, and only predicts a single label. However, if you look after the first stage where we find the document representations, you might be able to find the classes that are similar to the document.
3. This looks like doing multi-label text classification, and I would suggest you to try it with the similarity between document representations and class representations above.

Best,
Zihan
